### ISSUE TITLE
PELDA_02.c nekem nem működik

### ISSUE THREAD

**Issue by Alfika07** [fkhydra/C_programozas#1]
GCC-vel próbáltam lefordítani, de mindig ezt a hibaüzenetet írja:

```
./PELDA_02.c:5:18: error: initializer element is not constant
    5 | float eredmeny = (float)egesz1 / (float)egesz2;
      |                  ^
```

Gépem specifikációi:

- **Hardver**: HP Compaq 8200 Elite SFF PC
- **CPU**: Intel i5-2400 (4) @ 3.400GHz
- **RAM**: 4 GB RAM + 4 GB SWAP
- **OS**: Fedora Linux 37 (Workstation Edition) x86_64
- **Kernel**: Linux 6.0.15-300.fc37.x86_64
- **Shell**: zsh 5.9
- **GCC verzió**: 12.2.1 20221121 (Red Hat 12.2.1-4) (GCC)

Lehet, hogy én rontok el valamit, segítséget elfogadok.

**Comment by fkhydra** [comment]
A kérdéses sort a main() függvényen belülre rakva (egyből a >>main() {<< után) már le kell fordulnia a kódnak.
Ha így sem megy, akkor a GCC fordító beállításait kellene megnézni.
